### ISSUE TITLE
Need compile instructions...

### ISSUE THREAD

**Issue by Hanzyusuf** [usineur/ZeldaNSQ#2]
i'm a noob with all of this, but I am trying to compile the last commit (since i want 8-axis support) to a vpk, i have setup a cygwin mingw32 environment. there were some packages needed (sdl and libmikmod) and i found some links mentioned by you on one of your zelda3T port issues (same issue title).
link: https://github.com/usineur/Zelda3T/issues/4#issuecomment-343673540

there are two issues,
1: I don't know much about makefiles, but i think i will need to reference the vitasdk path in the makefile (and maybe other things too?), the makefile links you provided in the issue comment (link mentioned above) seem to have expired or moved or something, can you do the favor of providing those to me?
2: i cannot seem to install the SDL_mixer_1. 2.12 with the SDL version provided by you (in that same issue comment link) (btw i am using the makefile created by ./configure, and obviously not your version). This gives some error like WinMain@16, i am hoping you went through the same so maybe you know the solution.
<details>
<summary>the error:</summary>
/bin/sh ./libtool --mode=link gcc -o build/playwave.exe build/playwave.lo -I/usr/local/include/SDL -D_GNU_SOURCE=1 -Dmain=SDL_main -L/usr/local/lib -lSDLmain -lSDL -lmingw32 -mwindows build/libSDL_mixer.la
libtool: link: gcc -o build/.libs/playwave.exe build/.libs/playwave.o -I/usr/local/include/SDL -D_GNU_SOURCE=1 -Dmain=SDL_main -mwindows  -L/usr/local/lib /usr/local/lib/libSDLmain.a build/.libs/libSDL_mixer.dll.a -lmingw32 /usr/local/lib/libSDL.dll.a -luser32 -lgdi32 -lwinmm  -L/usr/local/lib
c:/psdk3v3/mingw/bin/../lib/gcc/mingw32/4.5.2/../../../libmingw32.a(main.o): In function `main':
C:\MinGW\msys\1.0\src\mingwrt/../mingw/main.c:73: undefined reference to `WinMain@16'
collect2: ld returned 1 exit status
make: *** [build/playwave.exe] Error 1
</details>

This is all assuming that I need the same libraries which you had used in the 3T port to compile this NSQ project.

**Comment by Hanzyusuf** [comment]
oh wait ignore my issue 2, since the errors were there because i had to install the libmikmod package before the sdl_mixer package.

**Comment by Hanzyusuf** [comment]
this link seems to discuss the same issue: https://discourse.libsdl.org/t/sdl-mixers-playwave-exe-linking-error-with-sdl-1-2-15-on-mingw32/18716/6

**Comment by usineur** [comment]
Those instructions are totally outdated.

You need to get current vitasdk toolchain (can be updated with `vitasdk-update` command). The only libs to have to rebuild are:
 - Latest revision of [vitaGL](https://github.com/Rinnegatamante/vitaGL), using: `make HAVE_SBRK=1 NO_DEBUG=1 HAVE_SHARK=2`
 - Latest revision of [imgui](https://github.com/Rinnegatamante/imgui-vita)
 - The sdl12_gl branch of [SDL 1.2](https://github.com/Rinnegatamante/SDL-Vita), using: `make -f Makefile.vita`

Why that, ZNSQ can be built using cmake

**Comment by Hanzyusuf** [comment]
> 
> 
> Those instructions are totally outdated.
> 
> You need to get current vitasdk toolchain (can be updated with `vitasdk-update` command). The only libs to have to rebuild are:
> 
>     * Latest revision of [vitaGL](https://github.com/Rinnegatamante/vitaGL), using: `make HAVE_SBRK=1 NO_DEBUG=1 HAVE_SHARK=2`
> 
>     * Latest revision of [imgui](https://github.com/Rinnegatamante/imgui-vita)
> 
>     * The sdl12_gl branch of [SDL 1.2](https://github.com/Rinnegatamante/SDL-Vita), using: `make -f Makefile.vita`
> 
> 
> With that, ZNSQ can be built using cmake

Thanks! I setup a clean environment again (it got too dirty!), installed vitasdk properly (followed all instructions on vitasdk.org), and also installed vitaGL, imgui and sdl 1.2 (in same order and with same flags/params as you mentioned above)

Although while installing sdl 1.2, i got an error in SDL_psp2video.c file:
<details>
<summary>error: </summary>
*src/video/psp2/SDL_psp2video.c: In function 'PSP2_FlipHWSurface':
src/video/psp2/SDL_psp2video.c:424:2: error: too few arguments to function 'vglSwapBuffers'
  424 |  vglSwapBuffers();
      |  ^~~~~~~~~~~~~~
In file included from src/video/psp2/SDL_psp2video.h:29,
                 from src/video/psp2/SDL_psp2video.c:45:
c:\msys64\usr\local\vitasdk\arm-vita-eabi\include\vitagl.h:506:6: note: declared here
  506 | void vglSwapBuffers(GLboolean has_commondialog);
      |      ^~~~~~~~~~~~~~
make: *** [<builtin>: src/video/psp2/SDL_psp2video.o] Error 1*
</details>
**i fixed that by passing 'GL_FALSE' as argument to function vglSwapBuffers on line 424 of 'SDL_psp2video.c' file, and it went smooth after that.**

*When attempting to build zelda, i cd into the zelda folder, then:
mkdir build
cd build
cmake ..
make*
**I get another error on file WindowManager.c:**
<details>
<summary>error:</summary>
*Building CXX object CMakeFiles/ZeldaNSQ.dir/src/engine/window/WindowManager.cpp.obj
C:/msys64/home/Hanzyusuf/zelda/src/engine/window/WindowManager.cpp:19:1: error: 'SDL_Shader' does not name a type
   19 | SDL_Shader shader = SDL_SHADER_NONE;
      | ^~~~~~~~~~
C:/msys64/home/Hanzyusuf/zelda/src/engine/window/WindowManager.cpp: In function 'void LoadSettings()':
C:/msys64/home/Hanzyusuf/zelda/src/engine/window/WindowManager.cpp:30:16: error: 'shader' was not declared in this scope
   30 |         fread(&shader, sizeof(SDL_Shader), 1, fp);
      |                ^~~~~~
C:/msys64/home/Hanzyusuf/zelda/src/engine/window/WindowManager.cpp:30:31: error: 'SDL_Shader' was not declared in this scope
   30 |         fread(&shader, sizeof(SDL_Shader), 1, fp);
      |                               ^~~~~~~~~~
C:/msys64/home/Hanzyusuf/zelda/src/engine/window/WindowManager.cpp: In function 'void SaveSettings()':
C:/msys64/home/Hanzyusuf/zelda/src/engine/window/WindowManager.cpp:44:17: error: 'shader' was not declared in this scope
   44 |         fwrite(&shader, sizeof(SDL_Shader), 1, fp);
      |                 ^~~~~~
C:/msys64/home/Hanzyusuf/zelda/src/engine/window/WindowManager.cpp:44:32: error: 'SDL_Shader' was not declared in this scope
   44 |         fwrite(&shader, sizeof(SDL_Shader), 1, fp);
      |                                ^~~~~~~~~~
C:/msys64/home/Hanzyusuf/zelda/src/engine/window/WindowManager.cpp: In function 'void SetSettings()':
C:/msys64/home/Hanzyusuf/zelda/src/engine/window/WindowManager.cpp:51:9: error: 'SDL_SetVideoModeScaling' was not declared in this scope; did you mean 'SDL_SetVideoMode'?
   51 |         SDL_SetVideoModeScaling(0, 0, 960, 544);
      |         ^~~~~~~~~~~~~~~~~~~~~~~
      |         SDL_SetVideoMode
C:/msys64/home/Hanzyusuf/zelda/src/engine/window/WindowManager.cpp:56:9: error: 'SDL_SetVideoModeScaling' was not declared in this scope; did you mean 'SDL_SetVideoMode'?
   56 |         SDL_SetVideoModeScaling(x, 0, sw, sh);
      |         ^~~~~~~~~~~~~~~~~~~~~~~
      |         SDL_SetVideoMode
C:/msys64/home/Hanzyusuf/zelda/src/engine/window/WindowManager.cpp:59:5: error: 'SDL_SetVideoModeBilinear' was not declared in this scope; did you mean 'SDL_SetVideoMode'?
   59 |     SDL_SetVideoModeBilinear(bilinear);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~
      |     SDL_SetVideoMode
C:/msys64/home/Hanzyusuf/zelda/src/engine/window/WindowManager.cpp:60:24: error: 'shader' was not declared in this scope
   60 |     SDL_SetVideoShader(shader);
      |                        ^~~~~~
C:/msys64/home/Hanzyusuf/zelda/src/engine/window/WindowManager.cpp:60:5: error: 'SDL_SetVideoShader' was not declared in this scope; did you mean 'SDL_SetVideoMode'?
   60 |     SDL_SetVideoShader(shader);
      |     ^~~~~~~~~~~~~~~~~~
      |     SDL_SetVideoMode
C:/msys64/home/Hanzyusuf/zelda/src/engine/window/WindowManager.cpp: In function 'void ImGui_callback()':
C:/msys64/home/Hanzyusuf/zelda/src/engine/window/WindowManager.cpp:110:54: error: 'shader' was not declared in this scope
  110 |                 if (ImGui::MenuItem("None", nullptr, shader == SDL_SHADER_NONE)) {
      |                                                      ^~~~~~
C:/msys64/home/Hanzyusuf/zelda/src/engine/window/WindowManager.cpp:110:64: error: 'SDL_SHADER_NONE' was not declared in this scope; did you mean 'GL_SHADER_TYPE'?
  110 |                 if (ImGui::MenuItem("None", nullptr, shader == SDL_SHADER_NONE)) {
      |                                                                ^~~~~~~~~~~~~~~
      |                                                                GL_SHADER_TYPE
C:/msys64/home/Hanzyusuf/zelda/src/engine/window/WindowManager.cpp:113:64: error: 'shader' was not declared in this scope
  113 |                 if (ImGui::MenuItem("Sharp Bilinear", nullptr, shader == SDL_SHADER_SHARP_BILINEAR_SIMPLE)) {
      |                                                                ^~~~~~
C:/msys64/home/Hanzyusuf/zelda/src/engine/window/WindowManager.cpp:113:74: error: 'SDL_SHADER_SHARP_BILINEAR_SIMPLE' was not declared in this scope
  113 |                 if (ImGui::MenuItem("Sharp Bilinear", nullptr, shader == SDL_SHADER_SHARP_BILINEAR_SIMPLE)) {
      |                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/msys64/home/Hanzyusuf/zelda/src/engine/window/WindowManager.cpp:116:76: error: 'shader' was not declared in this scope
  116 |                 if (ImGui::MenuItem("Sharp Bilinear (Scanlines)", nullptr, shader == SDL_SHADER_SHARP_BILINEAR)) {
      |                                                                            ^~~~~~
C:/msys64/home/Hanzyusuf/zelda/src/engine/window/WindowManager.cpp:116:86: error: 'SDL_SHADER_SHARP_BILINEAR' was not declared in this scope
  116 |                 if (ImGui::MenuItem("Sharp Bilinear (Scanlines)", nullptr, shader == SDL_SHADER_SHARP_BILINEAR)) {
      |                                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~
C:/msys64/home/Hanzyusuf/zelda/src/engine/window/WindowManager.cpp:119:56: error: 'shader' was not declared in this scope
  119 |                 if (ImGui::MenuItem("LCD 3x", nullptr, shader == SDL_SHADER_LCD3X)) {
      |                                                        ^~~~~~
C:/msys64/home/Hanzyusuf/zelda/src/engine/window/WindowManager.cpp:119:66: error: 'SDL_SHADER_LCD3X' was not declared in this scope
  119 |                 if (ImGui::MenuItem("LCD 3x", nullptr, shader == SDL_SHADER_LCD3X)) {
      |                                                                  ^~~~~~~~~~~~~~~~
C:/msys64/home/Hanzyusuf/zelda/src/engine/window/WindowManager.cpp:122:56: error: 'shader' was not declared in this scope
  122 |                 if (ImGui::MenuItem("xBR x2", nullptr, shader == SDL_SHADER_XBR_2X_FAST)) {
      |                                                        ^~~~~~
C:/msys64/home/Hanzyusuf/zelda/src/engine/window/WindowManager.cpp:122:66: error: 'SDL_SHADER_XBR_2X_FAST' was not declared in this scope
  122 |                 if (ImGui::MenuItem("xBR x2", nullptr, shader == SDL_SHADER_XBR_2X_FAST)) {
      |                                                                  ^~~~~~~~~~~~~~~~~~~~~~
C:/msys64/home/Hanzyusuf/zelda/src/engine/window/WindowManager.cpp: In member function 'int WindowManager::createWindow(std::string, std::string)':
C:/msys64/home/Hanzyusuf/zelda/src/engine/window/WindowManager.cpp:275:9: error: 'SDL_SetVideoCallback' was not declared in this scope; did you mean 'SDL_NewTimerCallback'?
  275 |         SDL_SetVideoCallback(ImGui_callback);
      |         ^~~~~~~~~~~~~~~~~~~~
      |         SDL_NewTimerCallback
make[2]: *** [CMakeFiles/ZeldaNSQ.dir/build.make:472: CMakeFiles/ZeldaNSQ.dir/src/engine/window/WindowManager.cpp.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:153: CMakeFiles/ZeldaNSQ.dir/all] Error 2
make: *** [Makefile:103: all] Error 2*
</details>

Would like some more help please!

**Comment by Hanzyusuf** [comment]
Sorry, my bad, i thought i did have to do **make install* after running make unless I plan on keeping the changes for after restart. Running 'make install' seems to have fixed it.

**It went to 98% then threw another error:**
<details>
<summary>error:</summary>
*c:/msys64/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/10.1.0/../../../../arm-vita-eabi/bin/ld.exe: cannot find -lSDL_mixer-modplug
collect2.exe: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/ZeldaNSQ.dir/build.make:3614: ZeldaNSQ] Error 1
make[1]: *** [CMakeFiles/Makefile2:153: CMakeFiles/ZeldaNSQ.dir/all] Error 2
make: *** [Makefile:103: all] Error 2*
</details>

btw if it matters, i did not run 'make install' with those flags and params you mentioned in that list, rather after running make with those flags and params, i directly ran 'make install'...

**Comment by Hanzyusuf** [comment]
never mind fixed it, thanks for the help!

I fixed that last *argument list too long* error by editing *build.make * file.
On line 660, each of the files to be copied to the vpk are addressed one by one with their own -a tags, i removed all the arguments of file paths which refer to files contained within the */data/* folder and instead add a single argument in place of all of them, **-a /home/Hanzyusuf/zelda/data/.=data/**

And the vpk finally generated, i'll update once i test it out!

**Comment by usineur** [comment]
SDL_mixer-modplug was a copy of SDL_mixer with MOD_MUSIC enabled, as the previous SDL_mixer lib from vitasdk was built without support of modplug.

"Argument list too long." error doesn't append for me on my linux env. Probably cygwin related problem.

No problem for the vpk. I close.

**Comment by Hanzyusuf** [comment]
hey, i was also trying to compile the version which you have already released, because the one i compiled (with all the latest commits) seems to hang a lot whenever link enters a new scene. 

The 1.1.1 stable version seems to be using older libraries since i get errors about undefined references to mikmod-exit, and lots of others when trying to compile. Can you help?

**Comment by usineur** [comment]
iirc i used to link with a version of SDL_mixer with modplug support.

MOD_MUSIC is enabled in https://github.com/vitasdk/packages/blob/master/sdl_mixer/Makefile.vita#L38 but MODPLUG_MUSIC is not. I thought it was, but no.

That's why I have [this "weird" depencendy](https://github.com/usineur/ZeldaNSQ/blob/vita/CMakeLists.txt#L38) in CMakeLists.txt, to avoid conflicts with the vitasdk's lib.

Try to rebuild sdl_mixer with modplug support.

**Comment by Hanzyusuf** [comment]
> iirc i used to link with a version of SDL_mixer with modplug support.
> 
> MOD_MUSIC is enabled in https://github.com/vitasdk/packages/blob/master/sdl_mixer/Makefile.vita#L38 but MODPLUG_MUSIC is not. I thought it was, but no.
> 
> That's why I have [this "weird" depencendy](https://github.com/usineur/ZeldaNSQ/blob/vita/CMakeLists.txt#L38) in CMakeLists.txt, to avoid conflicts with the vitasdk's lib.
> 
> Try to rebuild sdl_mixer with modplug support.

Sorry for this noob question, but how do i enable modplug support? Like is there some flag/parameter?

**Comment by usineur** [comment]
- Clone this repo: https://github.com/vitasdk/packages
- Go into sdl_mixer directory
- Add `-I$(VITASDK)/arm-vita-eabi/include/libmodplug -DMODPLUG_MUSIC` to CFLAGS
- Run `vita-makepkg`
- Install generated package with `vdpm`

**Comment by Hanzyusuf** [comment]
> 
> 
>     * Clone this repo: https://github.com/vitasdk/packages
> 
>     * Go into sdl_mixer directory
> 
>     * Add `-I$(VITASDK)/arm-vita-eabi/include/libmodplug -DMODPLUG_MUSIC` to CFLAGS
> 
>     * Run `vita-makepkg`
> 
>     * Install generated package with `vdpm`

doing this, i could compile upto 98% with no errors, but then this error pops up, and i have no idea how to fix this, i am sure this is the last error:
<details>
<summary>error:</summary>
c:/msys64/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/10.1.0/../../../../arm-vita-eabi/bin/ld.exe: cannot find -lSDL_mixer-modplug
collect2.exe: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/ZeldaNSQ.dir/build.make:3614: ZeldaNSQ] Error 1
make[1]: *** [CMakeFiles/Makefile2:153: CMakeFiles/ZeldaNSQ.dir/all] Error 2
make: *** [Makefile:103: all] Error 2
</details>

**Comment by usineur** [comment]
I don't think so, but meh, maybe. It works fine for me.
Can you to try to link with [this lib](https://www.ferb.fr/vita/libSDL_mixer-modplug.a) ?

**Comment by Hanzyusuf** [comment]
> 
> 
> I don't think so, but meh, maybe. It works fine for me.
> Can you to try to link with [this lib](https://www.ferb.fr/vita/libSDL_mixer-modplug.a) ?
> 
> Also here is the [VPK](https://www.ferb.fr/vita/ZeldaNSQ.vpk) based on latest changes, built with this lib.

omg thank you!

i will still try building though, no regrets!

**Comment by Hanzyusuf** [comment]
Building with that SDL_mixer-modplug.a file fixed all issues !

Finally at peace now. Thanks for your time.

**Comment by NicolasR** [comment]
Hello

Sorry for reopening this but i'm struggling with some compilation problems too.
Thanks for all the updated instructions but i still get this error on the linking process:

```/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/10.3.0/../../../../arm-vita-eabi/bin/ld: /usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/10.3.0/../../../../arm-vita-eabi/lib/libvitashark.a(vitashark.o): in function `shark_end':
(.text+0x8a): undefined reference to `sceShaccCgReleaseCompiler'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/ZeldaNSQ.dir/build.make:3594: ZeldaNSQ] Error 1
make[1]: *** [CMakeFiles/Makefile2:134: CMakeFiles/ZeldaNSQ.dir/all] Error 2```

I reinstalled my environment, reinstalled vitasdk multiple times. I don't know what i'm missing at all but it seems related to the vitasdk.

Can you help me ?

**Comment by usineur** [comment]
Hi,

it seems that latest commit(s) in vita-headers is/are not embedded when using vitasdk-update.

You can fix the problem this way:
- git clone https://github.com/vitasdk/vita-headers.git
- cd vitasdk && python3 build.py
- cp build/360/SceShaccCg.yml/*.a /usr/local/vitasdk/arm-vita-eabi/lib/

Should be fine this way.

**Comment by NicolasR** [comment]
Ok i didn't know what to do after building vita-headers. 

Thanks again for your time, your projects are compiling now.

**Comment by NicolasR** [comment]
Sorry for asking you again but i still have problems with your projects.
They are compiling without problem, but everytime i'm trying to use it, i get the error **C2-12828-1**
The dump seems to say "Data Abort Exception".

If i use vpk you released, absolutely no problem. But if i use mine or even the one you posted in this issue, it doesn't work.
I reinstalled my dev environnement, recompiled projects many times, reinstalled my vita..
I tried some samples of the vitasdk by building them and run them on my vita, it worked.

I'm running out of ideas...

**Comment by usineur** [comment]
This vpk runs fine for me, can you give it a try ?

Btw, does this error occur immediately or after a longer/shorter time?

**Comment by usineur** [comment]
This vpk runs fine for me, can you give it a try ? https://easyupload.io/ehahh0

Btw, does this error occur immediately or after a longer/shorter time?

**Comment by NicolasR** [comment]
This is not working for me too. The only one which is working is the one on release page.This error occured just after i start the app. I get a black screen and then it appeared. On data i can see that the app is able to create data folder but that's all.
I tried to reset and reinstall firmware again but it still happen.

Maybe is it related to a setting in vitaGL ?

**Comment by usineur** [comment]
Well, as vitashark is now required, you should need to install libshacccg if it's not done.

https://samilops2.gitbook.io/vita-troubleshooting-guide/shader-compiler/extract-libshacccg.suprx

**Comment by NicolasR** [comment]
Yes it's working now ! 
Thanks
